### ISSUE TITLE
AttributeError: 'CachedSession' object has no attribute 'remove_expired_responses'

### ISSUE THREAD

**Issue by cweiske** [dbr/tvdb_api#107]
When running tvnamer on Debian 12 I get:

```
2024-10-11 16:15:32,483 - requests_cache.backends.sqlite - DEBUG - Opening connection to /tmp/tvdb_api--u1000-py3.sqlite:redirects
Traceback (most recent call last):
  File "/usr/bin/tvnamer", line 6, in <module>
    tvnamer.main.main()
  File "/usr/share/tvnamer/main.py", line 474, in main
    tvnamer(paths = sorted(args))
  File "/usr/share/tvnamer/main.py", line 360, in tvnamer
    tvdb_instance = Tvdb(
                    ^^^^^
  File "/usr/lib/python3/dist-packages/tvdb_api.py", line 703, in __init__
    self.session.remove_expired_responses()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CachedSession' object has no attribute 'remove_expired_responses'
``` 

This is probably because the `python3-requests-cache` package
> It looks like CachedSession.remove_expired_responses() was deprecated in 1.0.0 and removed in 1.2.0

as described in https://aur.archlinux.org/packages/plover_plugins_manager#comment-988008

**Comment by StrangeNoises** [comment]
now also affecting tvnamer 3.0.4 on ubuntu 25.04 (in late beta). Error stack trace is slightly different in a way that probably doesn't matter:

```
Loading config: /home/rachel/.config/tvnamer/tvnamer.json
####################
# Starting tvnamer
# Found 1 episode
Traceback (most recent call last):
  File "/usr/bin/tvnamer", line 6, in <module>
    tvnamer.main.main()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/share/tvnamer/main.py", line 474, in main
    tvnamer(paths = sorted(args))
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/tvnamer/main.py", line 360, in tvnamer
    tvdb_instance = Tvdb(
        interactive = not Config['select_first'],
    ...<4 lines>...
        apikey=api_key,
    )
  File "/usr/lib/python3/dist-packages/tvdb_api.py", line 703, in __init__
    self.session.remove_expired_responses()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CachedSession' object has no attribute 'remove_expired_responses'
```

Versions:

```
$ tvnamer --version
tvnamer version: 3.0.4
tvdb_api version: 3.1.0

$ apt-cache policy tvnamer
tvnamer:
  Installed: 3.0.4-2
  Candidate: 3.0.4-2
  Version table:
 *** 3.0.4-2 500
        500 http://gb.archive.ubuntu.com/ubuntu plucky/universe amd64 Packages
        100 /var/lib/dpkg/status

$ apt-cache policy python3-requests-cache
python3-requests-cache:
  Installed: 1.2.1-1
  Candidate: 1.2.1-1
  Version table:
 *** 1.2.1-1 500
        500 http://gb.archive.ubuntu.com/ubuntu plucky/universe amd64 Packages
        100 /var/lib/dpkg/status
```

Knowing Ubuntu, the tvnamer universe package probably won't get an update in 25.04's lifetime, so I'd expect to be installing one outside of normal package management if it promised a fix, but just at the moment, it's got the latest version.

**Comment by BlueGarm** [comment]
Still same issue with Ubuntu 25.10. 

No fix planned in futur ?
